### ISSUE TITLE
Select the sort order for columns in list view

### ISSUE THREAD

**Issue by JoKo1959** [christianwannerstedt/obsidian-tags-overview#15]
The list view has enormous potential. It would be great to be able to select the sort order for added columns, e.g. the date of birth from the properties. If the birth dates were sorted in ascending order, I would have a timeline, which I am urgently looking for. Thank you so much.

**Comment by christianwannerstedt** [comment]
Hey! Thanks for the feedback, it's definitely a good idea to implement this. I'll look into it.

**Comment by christianwannerstedt** [comment]
This is now fixed in the latest release ([0.1.9](https://github.com/christianwannerstedt/obsidian-tags-overview/releases/tag/0.1.9))

**Comment by JoKo1959** [comment]
Sorting by property: thanks for this extension of the functionality. However, the tags panel becomes empty when I try to sort by property. Thanks for your help.

**Comment by christianwannerstedt** [comment]
Yes, you're right, there seems to be an issue now if the property type is not a text string. I'll look into it asap.

**Comment by christianwannerstedt** [comment]
The issue should now be fixed in the latest release ([0.1.11](https://github.com/christianwannerstedt/obsidian-tags-overview/releases/tag/0.1.11))

**Comment by JoKo1959** [comment]
Thank you for the update. When I select text from the properties, the column can be sorted by it without any problems. Unfortunately, this still doesn't work with date fields, even with the update 0.1.11, which I just downloaded. An empty page appears when sorting for date. Thank you very much for this really fantastic plugin and your help.

**Comment by christianwannerstedt** [comment]
Ah, tnx for helping me sort this one out. It should hopefully be fixed now in the latest release ([0.1.12](https://github.com/christianwannerstedt/obsidian-tags-overview/releases/tag/0.1.12))

**Comment by JoKo1959** [comment]
Great; thank you so much; it now works perfectly; very helpful functionality!

**Comment by christianwannerstedt** [comment]
Great, I'm glad to hear it's working better now!
FYI, I just created a new release ([1.0.0](https://github.com/christianwannerstedt/obsidian-tags-overview/releases/tag/1.0.0)) in which it's possible to add additional filters based on properties. I thought it might be useful for you since you seem to be using properties :). You can find additional info in the readme.

**Comment by JoKo1959** [comment]
Thanks; I use the plugin a lot; it's very useful for me; and the latest version offers even better functionality. Thank you for your efforts!
Johannes Kornhuber

Von: christianwannerstedt ***@***.***>
Gesendet: Sonntag, 7. Januar 2024 22:23
An: christianwannerstedt/obsidian-tags-overview ***@***.***>
Cc: Kornhuber, Johannes ***@***.***>; Author ***@***.***>
Betreff: Re: [christianwannerstedt/obsidian-tags-overview] Select the sort order for columns in list view (Issue #15)


Great, I'm glad to hear it's working better now!
FYI, I just created a new release (1.0.0<https://github.com/christianwannerstedt/obsidian-tags-overview/releases/tag/1.0.0>) in which it's possible to add additional filters based on properties. I thought it might be useful for you since you seem to be using properties :). You can find additional info in the readme.

**Comment by shcherbakov-timur** [comment]
The sorting by property doesn't work(
When I choose sorting everything disappears

I see that people write that the problem is solved, but it's not true
I use the version 1.0.4
